(() => {
'use strict';
const $=id=>document.getElementById(id), qsa=s=>[...document.querySelectorAll(s)];
const STORE='pei_docente_v42';
const num=v=>{const n=parseFloat(String(v??'').replace(',','.'));return Number.isFinite(n)?n:0};
const fmt=(n,d=1)=>Number(n||0).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let db={codes:[],assessments:{},current:null};
let project=null, rubric=[];
function load(){try{db={...db,...JSON.parse(localStorage.getItem(STORE)||'{}')};}catch(e){}}function save(){localStorage.setItem(STORE,JSON.stringify(db));renderMetrics();}
function dl(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
function normalizeCodeClass(v){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9]+/g,'-').replace(/^-|-$/g,'')}
function generateCodes(){const year=Math.round(num($('codeYear').value))||new Date().getFullYear(),cl=normalizeCodeClass($('codeClass').value),qty=Math.max(1,Math.min(50,Math.round(num($('codeQty').value)||1))),start=Math.max(1,Math.round(num($('codeStart').value)||1));db.codes=Array.from({length:qty},(_,i)=>{const n=start+i,code=`PEI-${year}-${cl?cl+'-':''}T${String(n).padStart(2,'0')}`;const old=db.codes.find(x=>x.code===code)||{};return{code,index:n,company:old.company||'',members:old.members||'',status:old.status||'NÃO ENTREGUE'}});save();renderCodes()}
function renderCodes(){const b=$('codesBody');if(!db.codes.length){b.innerHTML='<tr><td colspan="5">Nenhum código gerado.</td></tr>';return}b.innerHTML=db.codes.map((x,i)=>`<tr><td>${i+1}</td><td><strong>${esc(x.code)}</strong></td><td>${esc(x.company||'—')}</td><td>${esc(x.members||'—')}</td><td><span class="badge ${x.status==='AVALIADO'?'green':x.status==='ENTREGUE'?'orange':'red'}">${x.status}</span></td></tr>`).join('')}
function exportCodes(){if(!db.codes.length)generateCodes();const rows=[['N','Codigo','Empresa_Trio','Integrantes','Status'],...db.codes.map((x,i)=>[i+1,x.code,x.company,x.members,x.status])];const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;dl(new Blob(['\ufeff'+rows.map(r=>r.map(q).join(';')).join('\n')],{type:'text/csv;charset=utf-8'}),'Codigos_Trios_PEI.csv')}

function memberNames(p){return (p.team?.members||[]).map(m=>m.name).filter(Boolean).join(' • ')}
function teamParticipation(p){return (p.team?.members||[]).reduce((s,m)=>s+num(m.participation),0)}
function motorComplete(m){return !!(m.method&&num(m.current)>0&&m.cable&&m.breaker&&m.device&&m.overload)}
function materialComplete(m){return !!(m.description&&num(m.qty)>0&&String(m.unitPrice??'').trim()!=='')}
function memdescFilled(p){return Object.values(p.memdesc||{}).filter(v=>String(v||'').trim().length>40).length}
function lightingComplete(r){return num(r.flux)>0&&num(r.uf)>0&&num(r.mf)>0&&num(r.adopted)>0&&num(r.watt)>0}
function driveDecisionGood(m){return !!(m.method&&String(m.justification||'').trim().length>=20&&m.driveEvaluation?.level!=='fail')}
function evalItem(label,ok,detail,weight=1){return{label,ok:!!ok,detail,weight}}
function criterion(id,title,max,description,evidence){const total=evidence.reduce((s,e)=>s+e.weight,0)||1,got=evidence.reduce((s,e)=>s+(e.ok?e.weight:0),0),ratio=got/total,suggested=Math.round(max*ratio*10)/10;return{id,title,max,description,evidence,ratio,suggested,assigned:suggested,comment:''}}
function buildRubric(p){
 const members=p.team?.members||[], motors=p.motors||[], mats=p.materials||[], lighting=p.lighting||[], calc=p.calcLog||[];
 const q=p.qgbt||{},c=p.ccm||{},s=p.substation||{},sp=p.spda||{};
 const validDrive=motors.filter(driveDecisionGood).length, completeMotors=motors.filter(motorComplete).length;
 const directViol=motors.filter(m=>m.method==='Partida direta'&&((num(m.voltage)<=220&&num(m.cv)>5.01)||(num(m.voltage)>220&&num(m.cv)>7.51))).length;
 const ownedCalc=calc.filter(x=>x.ownerName).length;
 const materialOk=mats.filter(materialComplete).length;
 return [
  criterion('team','1. Empresa fictícia, trio e participação',5,'Identificação profissional da empresa/equipe e distribuição das responsabilidades.',[
   evalItem('Empresa fictícia identificada',p.team?.companyName,'Empresa: '+(p.team?.companyName||'não informada'),2),evalItem('Três integrantes cadastrados',members.length===3&&members.every(m=>m.name),memberNames(p)||'Integrantes incompletos',2),evalItem('Participação totaliza 100%',Math.abs(teamParticipation(p)-100)<.01,'Total declarado: '+fmt(teamParticipation(p),0)+'%',1),evalItem('Funções e responsabilidades registradas',members.every(m=>m.role&&m.responsibilities),'Divisão de responsabilidades da equipe',1)]),
  criterion('drives','2. Engenharia de acionamentos',15,'Escolha e justificativa de partida direta, SSW07 ou CFW500 conforme a condição do processo.',[
   evalItem('10 acionamentos escolhidos',motors.length===10&&motors.every(m=>m.method),`${motors.filter(m=>m.method).length}/10 escolhidos`,3),evalItem('10 justificativas técnicas',validDrive===10,`${validDrive}/10 decisões tecnicamente justificadas`,4),evalItem('Sem partida direta fora do limite da UC',directViol===0,directViol?`${directViol} violação(ões) encontrada(s)`:'Nenhuma violação',3),evalItem('Parâmetros dos drives registrados',motors.filter(m=>m.method==='Partida direta'||Object.values(m.driveConfig||{}).filter(Boolean).length>=3).length>=8,'Especificações/parametrização preenchidas',2)]),
  criterion('loads','3. Quadro de cargas e dimensionamento dos motores',15,'Coerência entre dados das cargas, correntes, cabos, proteções e componentes.',[
   evalItem('10 motores com corrente calculada',motors.length===10&&motors.every(m=>num(m.current)>0),`${motors.filter(m=>num(m.current)>0).length}/10`,3),evalItem('Cabos definidos para 10 motores',motors.length===10&&motors.every(m=>m.cable),`${motors.filter(m=>m.cable).length}/10`,3),evalItem('Proteções definidas',motors.length===10&&motors.every(m=>m.breaker),`${motors.filter(m=>m.breaker).length}/10`,3),evalItem('Contator/drive e relé definidos',completeMotors===10,`${completeMotors}/10 motores completos`,3),evalItem('Distâncias e dados-base preservados',motors.length===10&&motors.every(m=>num(m.distance)>0),'Percursos das cargas disponíveis',1)]),
  criterion('qgbt','4. QGBT',10,'Dimensionamento e especificação do quadro geral de baixa tensão.',[
   evalItem('Disjuntor geral definido',q.breaker,q.breaker||'não definido',2),evalItem('Icu/Ics ou capacidade de interrupção registrada',num(q.icu)>0,q.icu?`${q.icu} kA`:'não registrada',2),evalItem('Barramento definido',q.bus,q.bus||'não definido',2),evalItem('Alimentador definido',q.cable,q.cable||'não definido',2),evalItem('DPS / N / PE / seletividade documentados',q.dps&&q.neutral&&q.pe&&q.selectivity,'Proteções complementares e distribuição',2)]),
  criterion('ccm','5. CCM e gavetas de acionamento',12,'Coerência entre o CCM, as dez saídas e os acionamentos escolhidos.',[
   evalItem('Barramento do CCM definido',c.bus,c.bus||'não definido',2),evalItem('Icc do CCM registrada',num(c.icc)>0,c.icc?`${c.icc} kA`:'não registrada',2),evalItem('Disjuntor geral do CCM definido',c.mainBreaker,c.mainBreaker||'não definido',2),evalItem('10 gavetas coerentes com o quadro de cargas',completeMotors===10,`${completeMotors}/10`,4),evalItem('IP/forma/reserva registrados',c.ip&&c.form&&c.reserve,'Dados construtivos do CCM',1)]),
  criterion('substation','6. Subestação e transformação',12,'Transformador, correntes, curto-circuito e proteção da entrada.',[
   evalItem('Transformador definido',num(s.trafo)>0,s.trafo?`${s.trafo} kVA`:'não definido',2),evalItem('Correntes primária e secundária registradas',num(s.ip)>0&&num(s.is)>0,`Ip ${s.ip||'—'} A • Is ${s.is||'—'} A`,2),evalItem('Curto-circuito registrado',num(s.icc)>0,s.icc?`${s.icc} kA`:'não registrado',2),evalItem('Proteção MT registrada',s.mtProtection,s.mtProtection||'não registrada',2),evalItem('Disjuntor BT registrado',s.btBreaker,s.btBreaker||'não registrado',1),evalItem('Medição/TC/TP/para-raios/terra registrados',s.metering&&s.tc&&s.tp&&s.arrester&&s.groundCable,'Conjunto de entrada documentado',2)]),
  criterion('lighting','7. Projeto luminotécnico',8,'Cálculo por ambiente, luminárias adotadas e potência instalada.',[
   evalItem('Todos os ambientes calculados',lighting.length>=7&&lighting.every(lightingComplete),`${lighting.filter(lightingComplete).length}/${lighting.length} ambientes completos`,5),evalItem('Modelos de luminárias especificados',lighting.every(r=>r.model),`${lighting.filter(r=>r.model).length}/${lighting.length}`,2)]),
  criterion('spda','8. SPDA, BEP e aterramento',7,'Definição dos principais parâmetros de proteção contra descargas e equipotencialização.',[
   evalItem('Classe e método do SPDA definidos',sp.class&&sp.method,`${sp.class||'—'} • ${sp.method||'—'}`,2),evalItem('Descidas e seções registradas',sp.downs&&sp.downSection,'Descidas/condutores',1),evalItem('Malha, hastes e resistividade registradas',sp.gridSection&&sp.rods&&sp.rho,'Aterramento documentado',2),evalItem('BEP/DPS/equipotencialização registrados',sp.bepSection&&sp.dps&&sp.bonding,'Proteção e equipotencialização',1)]),
  criterion('memcalc','9. Memória de cálculo',7,'Registro rastreável dos principais cálculos e responsável por cada cálculo.',[
   evalItem('Quantidade mínima de cálculos registrada',calc.length>=8,`${calc.length} cálculos`,3),evalItem('Cálculos identificam responsável',calc.length>0&&ownedCalc===calc.length,`${ownedCalc}/${calc.length} com responsável`,2),evalItem('Diversidade de categorias',new Set(calc.map(x=>x.category).filter(Boolean)).size>=4,`${new Set(calc.map(x=>x.category).filter(Boolean)).size} categorias`,1)]),
  criterion('memdesc','10. Memorial descritivo',4,'Texto técnico coerente com os dados efetivamente adotados no projeto.',[
   evalItem('Seções principais preenchidas',memdescFilled(p)>=8,`${memdescFilled(p)}/10 seções com conteúdo`,3),evalItem('Cliente e empresa aparecem na documentação',p.client?.name&&p.team?.companyName,'Identificação documental',1)]),
  criterion('materials','11. Lista de materiais e orçamento',3,'Itens, quantidades, preços unitários e totalização do projeto.',[
   evalItem('Lista de materiais criada',mats.length>=10,`${mats.length} itens`,1),evalItem('Itens com quantidade e preço',mats.length>0&&materialOk===mats.length,`${materialOk}/${mats.length} completos`,2)]),
  criterion('coherence','12. Coerência e entrega final',2,'Consistência documental, revisão e completude global.',[
   evalItem('Código individual e revisão registrados',p.meta?.code&&p.revision?.number,`${p.meta?.code||'—'} • ${p.revision?.number||'—'}`,1),evalItem('Arquivo de entrega gerado pela plataforma',p.submission?.type==='PEI-TRIO-ENTREGA',p.submission?`Conclusão declarada: ${p.submission.completion||0}%`:'JSON de projeto, não arquivo formal de entrega',1)])
 ];
}
function analyzeProject(p){rubric=buildRubric(p);const saved=db.assessments[p.meta?.code];if(saved?.rubric){rubric.forEach(r=>{const old=saved.rubric.find(x=>x.id===r.id);if(old){r.assigned=old.assigned;r.comment=old.comment||''}})};renderProjectOverview();renderRubric();updateScore();}
function renderProjectOverview(){const p=project, members=memberNames(p)||'—';$('emptyAssessment').classList.add('hidden');$('projectOverview').classList.remove('hidden');$('assessmentWorkspace').classList.remove('hidden');$('projectOverview').innerHTML=`<div class="summary-grid"><div class="summary-card"><small>Código</small><strong>${esc(p.meta?.code||'—')}</strong></div><div class="summary-card"><small>Empresa</small><strong>${esc(p.team?.companyName||'—')}</strong></div><div class="summary-card"><small>Trio</small><strong>${esc(members)}</strong></div><div class="summary-card"><small>Cliente</small><strong>${esc(p.client?.name||'—')}</strong></div></div><div class="callout"><strong>Arquivo:</strong> ${p.submission?.type==='PEI-TRIO-ENTREGA'?'Entrega formal gerada pela plataforma':'Projeto JSON importado'} • Revisão ${esc(p.revision?.number||'—')} • ${p.calcLog?.length||0} cálculos registrados • ${p.materials?.length||0} itens de materiais.</div>`}
function renderRubric(){$('rubricList').innerHTML=rubric.map((r,i)=>`<article class="rubric-card"><div class="rubric-head"><div class="rubric-title"><h3>${esc(r.title)}</h3><p>${esc(r.description)}</p></div><div class="rubric-score"><small>Sugerido</small><strong>${fmt(r.suggested,1)} / ${r.max}</strong></div><div class="rubric-points field"><label>Nota docente</label><input type="number" min="0" max="${r.max}" step="0.1" data-points="${i}" value="${r.assigned}"></div></div><div class="evidence-grid">${r.evidence.map(e=>`<div class="evidence ${e.ok?'ok':'fail'}"><strong>${e.ok?'✓ ATINGIDO':'× PENDENTE'} — ${esc(e.label)}</strong><span>${esc(e.detail)}</span></div>`).join('')}</div><div class="field criterion-comment"><label>Comentário do docente neste critério</label><textarea data-comment="${i}" placeholder="Opcional...">${esc(r.comment||'')}</textarea></div></article>`).join('');qsa('[data-points]').forEach(el=>el.addEventListener('input',()=>{const r=rubric[+el.dataset.points];r.assigned=Math.max(0,Math.min(r.max,num(el.value)));updateScore()}));qsa('[data-comment]').forEach(el=>el.addEventListener('input',()=>rubric[+el.dataset.comment].comment=el.value))}
function totalScore(){return rubric.reduce((s,r)=>s+num(r.assigned),0)}function achievedCount(){return rubric.filter(r=>num(r.assigned)>=r.max*.7).length}
function concept(v){if(v>=90)return'Excelente';if(v>=80)return'Muito bom';if(v>=70)return'Bom / competente';if(v>=60)return'Parcialmente competente';return'Requer recuperação / revisão'}
function updateScore(){const s=totalScore(),a=achievedCount();$('score100').textContent=`${fmt(s,1)} / 100`;$('score10').textContent=`${fmt(s/10,1)} / 10,0`;$('criteriaAchieved').textContent=`${a} / ${rubric.length}`;$('gradeConcept').textContent=concept(s);$('currentScore').textContent=project?fmt(s/10,1):'—';$('criteriaSummary').innerHTML=rubric.map(r=>{const ratio=r.max?num(r.assigned)/r.max:0,cls=ratio>=.7?'ok':ratio>=.5?'partial':'fail';return`<div class="criteria-result ${cls}"><div class="ico">${ratio>=.7?'✓':ratio>=.5?'!':'×'}</div><div><strong>${esc(r.title)}</strong><small>${r.evidence.filter(e=>e.ok).length}/${r.evidence.length} evidências automáticas atingidas. ${r.comment?esc(r.comment):''}</small></div><strong>${fmt(r.assigned,1)}/${r.max}</strong></div>`}).join('');renderMetrics()}
function saveAssessment(){if(!project)return;const code=project.meta?.code||'SEM-CODIGO';db.assessments[code]={code,company:project.team?.companyName||'',members:memberNames(project),client:project.client?.name||'',score:totalScore(),score10:totalScore()/10,concept:concept(totalScore()),criteriaAchieved:achievedCount(),rubric:rubric.map(r=>({...r})),strengths:$('teacherStrengths').value,improve:$('teacherImprove').value,finalNote:$('teacherFinalNote').value,updatedAt:new Date().toISOString(),project};db.current=code;const c=db.codes.find(x=>x.code===code);if(c){c.company=project.team?.companyName||'';c.members=memberNames(project);c.status='AVALIADO'}save();renderCodes();renderHistory();}
function useSuggested(){rubric.forEach(r=>r.assigned=r.suggested);renderRubric();updateScore()}
function importSubmission(file){const rd=new FileReader();rd.onload=()=>{try{const p=JSON.parse(rd.result);if(!p?.schema?.startsWith('PEI-PROJETISTA-INTEGRADO'))throw new Error('Arquivo não pertence ao PEI Projetista Integrado.');project=p;const code=p.meta?.code||'SEM-CODIGO';const c=db.codes.find(x=>x.code===code);if(c){c.company=p.team?.companyName||'';c.members=memberNames(p);c.status='ENTREGUE'}save();analyzeProject(p);renderCodes();}catch(e){alert('Não foi possível analisar o arquivo: '+e.message)}};rd.readAsText(file)}
function buildReport(){if(!project)return'';const s=totalScore(),date=new Date().toLocaleDateString('pt-BR');const rows=rubric.map(r=>`<tr><td>${esc(r.title)}</td><td>${r.max}</td><td>${fmt(r.assigned,1)}</td><td>${num(r.assigned)>=r.max*.7?'<span class="achieved">ATINGIDO</span>':'<span class="pending">NÃO ATINGIDO / PARCIAL</span>'}</td></tr>`).join('');const details=rubric.map(r=>`<h3>${esc(r.title)} — ${fmt(r.assigned,1)}/${r.max}</h3><ul>${r.evidence.map(e=>`<li><strong>${e.ok?'ATINGIDO':'PENDENTE'}:</strong> ${esc(e.label)} — ${esc(e.detail)}</li>`).join('')}</ul>${r.comment?`<p><strong>Comentário do docente:</strong> ${esc(r.comment)}</p>`:''}`).join('');return`<section class="report-page report-cover"><img src="assets/senai_logo.webp"><h1>RELATÓRIO DE AVALIAÇÃO DO PROJETO ELÉTRICO INDUSTRIAL</h1><h2>${esc(project.team?.companyName||'Empresa do trio')}</h2><p>${esc(memberNames(project))}</p><p><strong>Código:</strong> ${esc(project.meta?.code||'—')} • <strong>Revisão:</strong> ${esc(project.revision?.number||'—')}</p><div class="report-score">${fmt(s/10,1)} / 10,0</div><p>${esc(concept(s))}</p><p>Emissão da avaliação: ${date}</p></section><section class="report-page"><h2>1. Resultado por critérios</h2><table><thead><tr><th>Critério</th><th>Máx.</th><th>Obtido</th><th>Situação</th></tr></thead><tbody>${rows}</tbody><tfoot><tr><th>TOTAL</th><th>100</th><th>${fmt(s,1)}</th><th>${achievedCount()}/${rubric.length} critérios atingidos</th></tr></tfoot></table><h3>Pontos fortes</h3><p>${esc($('teacherStrengths').value||'Não informado.')}</p><h3>Pontos a melhorar</h3><p>${esc($('teacherImprove').value||'Não informado.')}</p><h3>Parecer final</h3><p>${esc($('teacherFinalNote').value||'Não informado.')}</p></section><section class="report-page"><h2>2. Evidências e critérios atingidos</h2>${details}</section>`}
function generateReportPdf(){saveAssessment();const root=$('assessmentReport');root.innerHTML=buildReport();root.classList.remove('hidden');const code=project.meta?.code||'TRIO';if(window.html2pdf){html2pdf().set({margin:6,filename:`AVALIACAO_${code}.pdf`,image:{type:'jpeg',quality:.96},html2canvas:{scale:1.6,useCORS:true},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css','legacy']}}).from(root).save().then(()=>root.classList.add('hidden')).catch(()=>{root.classList.add('hidden');window.print()})}else window.print()}
function exportAssessment(){saveAssessment();const a=db.assessments[project.meta?.code];dl(new Blob([JSON.stringify(a,null,2)],{type:'application/json'}),`AVALIACAO_${project.meta?.code||'TRIO'}.json`)}
function renderHistory(){const vals=Object.values(db.assessments).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));$('historyList').innerHTML=vals.length?vals.map(a=>`<article class="history-card"><h3>${esc(a.company||a.code)}</h3><p>${esc(a.code)}<br><small>${esc(a.members)}</small></p><div class="score">${fmt(a.score10,1)}</div><p>${esc(a.concept)} • ${a.criteriaAchieved}/12 critérios</p><div class="actions-row"><button class="btn" data-open-assessment="${esc(a.code)}">Abrir</button><button class="btn danger" data-delete-assessment="${esc(a.code)}">Excluir</button></div></article>`).join(''):'<div class="callout">Nenhuma avaliação salva ainda.</div>';qsa('[data-open-assessment]').forEach(b=>b.onclick=()=>{const a=db.assessments[b.dataset.openAssessment];project=a.project;rubric=buildRubric(project);rubric.forEach(r=>{const old=a.rubric.find(x=>x.id===r.id);if(old){r.assigned=old.assigned;r.comment=old.comment||''}});$('teacherStrengths').value=a.strengths||'';$('teacherImprove').value=a.improve||'';$('teacherFinalNote').value=a.finalNote||'';showTab('assessment');renderProjectOverview();renderRubric();updateScore()});qsa('[data-delete-assessment]').forEach(b=>b.onclick=()=>{if(confirm('Excluir esta avaliação do histórico local?')){delete db.assessments[b.dataset.deleteAssessment];save();renderHistory()}})}
function renderMetrics(){$('codesCount').textContent=db.codes.length;$('projectsCount').textContent=Object.keys(db.assessments).length;if(project){const checks=rubric.flatMap(r=>r.evidence),pct=checks.length?Math.round(100*checks.filter(e=>e.ok).length/checks.length):0;$('currentCompletion').textContent=pct+'%'}else $('currentCompletion').textContent='—'}
function showTab(name){qsa('.teacher-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));qsa('.teacher-tab').forEach(t=>t.classList.toggle('active',t.id==='tab-'+name));if(name==='history')renderHistory()}
qsa('.teacher-tabs button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$('generateCodes').onclick=generateCodes;$('exportCodesCsv').onclick=exportCodes;$('clearCodes').onclick=()=>{if(confirm('Apagar a lista de códigos gerados? As avaliações salvas serão mantidas.')){db.codes=[];save();renderCodes()}};$('importSubmission').onchange=e=>{const f=e.target.files?.[0];if(f)importSubmission(f);e.target.value=''};$('useSuggested').onclick=useSuggested;$('generateGrade').onclick=()=>{saveAssessment();updateScore();alert(`Nota gerada: ${fmt(totalScore()/10,1)} / 10,0. O relatório registra os critérios atingidos e pendentes.`)};$('pdfAssessment').onclick=generateReportPdf;$('exportAssessment').onclick=exportAssessment;$('resetTeacher').onclick=()=>{if(confirm('Apagar códigos e avaliações armazenados neste navegador?')){localStorage.removeItem(STORE);location.reload()}};$('themeBtn').onclick=()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'light':'dark'};
load();renderCodes();renderHistory();renderMetrics();
})();